"""add auth provider

Revision ID: 8807e577f92f
Revises: 
Create Date: 2026-06-05 15:57:45.306212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8807e577f92f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('transactions')
    op.drop_table('product')
    op.drop_table('stores')
    op.drop_table('audit_log')
    op.drop_table('customers')
    op.drop_table('inventory')
    op.drop_table('integrity_log')
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'auth_provider_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('profiles_username_key'), 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_constraint(op.f('profiles_store_id_fkey'), 'profiles', type_='foreignkey')
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(op.f('profiles_store_id_fkey'), 'profiles', 'stores', ['store_id'], ['store_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.create_unique_constraint(op.f('profiles_username_key'), 'profiles', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('profiles', 'auth_provider_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('integrity_log',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_included', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_excluded', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_fixed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('exclusion_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fix_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('integrity_log_submission_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('integrity_log_pkey')),
    sa.UniqueConstraint('submission_id', name=op.f('integrity_log_submission_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reorder_level', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('inventory_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name=op.f('inventory_store_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('inventory_pkey')),
    sa.UniqueConstraint('store_id', 'product_id', name=op.f('inventory_store_id_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loyalty_card_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('demographic_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joined_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.CheckConstraint("demographic_group::text = ANY (ARRAY['Gen Z'::character varying, 'Millennial'::character varying, 'Gen X'::character varying, 'Senior'::character varying]::text[])", name=op.f('customers_demographic_group_check')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customers_pkey')),
    sa.UniqueConstraint('loyalty_card_number', name=op.f('customers_loyalty_card_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("severity::text = ANY (ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying]::text[])", name=op.f('audit_log_severity_check')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name=op.f('audit_log_store_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('audit_log_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('audit_log_pkey'))
    )
    op.create_table('stores',
    sa.Column('store_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('store_id', name=op.f('stores_pkey')),
    sa.UniqueConstraint('store_name', name=op.f('stores_store_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('product_pkey'))
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('transactions_quantity_check')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('transactions_customer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('transactions_product_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name=op.f('transactions_store_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('transactions_submission_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('transactions_pkey'))
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('week_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])", name=op.f('submissions_status_check')),
    sa.CheckConstraint('period_month >= 1 AND period_month <= 12', name=op.f('submissions_period_month_check')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name=op.f('submissions_store_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('submissions_pkey'))
    )
    # ### end Alembic commands ###
